/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthEmailRouteImport } from './routes/auth/email'
import { Route as AuthExternalRouteImport } from './routes/auth/external'
import { Route as AuthedAdminConsultantsRouteImport } from './routes/_authed/admin/consultants'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: '/auth/email',
  path: '/auth/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExternalRoute = AuthExternalRouteImport.update({
  id: '/auth/external',
  path: '/auth/external',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminConsultantsRoute = AuthedAdminConsultantsRouteImport.update({
  id: '/admin/consultants',
  path: '/admin/consultants',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/profile': typeof AuthedProfileRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/external': typeof AuthExternalRoute
  '/admin/consultants': typeof AuthedAdminConsultantsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/profile': typeof AuthedProfileRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/external': typeof AuthExternalRoute
  '/': typeof AuthedIndexRoute
  '/admin/consultants': typeof AuthedAdminConsultantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/external': typeof AuthExternalRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/consultants': typeof AuthedAdminConsultantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/profile'
    | '/auth/email'
    | '/auth/external'
    | '/admin/consultants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/profile'
    | '/auth/email'
    | '/auth/external'
    | '/'
    | '/admin/consultants'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/profile'
    | '/auth/email'
    | '/auth/external'
    | '/_authed/'
    | '/_authed/admin/consultants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthEmailRoute: typeof AuthEmailRoute
  AuthExternalRoute: typeof AuthExternalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/email': {
      id: '/auth/email'
      path: '/auth/email'
      fullPath: '/auth/email'
      preLoaderRoute: typeof AuthEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/external': {
      id: '/auth/external'
      path: '/auth/external'
      fullPath: '/auth/external'
      preLoaderRoute: typeof AuthExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/consultants': {
      id: '/_authed/admin/consultants'
      path: '/admin/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AuthedAdminConsultantsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminConsultantsRoute: typeof AuthedAdminConsultantsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminConsultantsRoute: AuthedAdminConsultantsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthExternalRoute: AuthExternalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
