<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>carenest-migrations</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareNest.ServiceDefaults\CareNest.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Modules\CareNest.Identity\CareNest.Identity.csproj" />
  </ItemGroup>

</Project>
